apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: devsu-python-app
  name: devsu-python-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: devsu-python-app
status:
  loadBalancer: {}
