apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: development
images:
- name: devsu-python-app-ecr
  newName: devsu-python-app-ecr
  newTag: latest-v2
secretGenerator:
  - name: devsu-python-app-secrets
    behavior: replace
    envs:
      - secret.env
generatorOptions:
  disableNameSuffixHash: true

