apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: development
images:
- name: devsu-python-app-ecr
  newName: devsu-python-app-ecr
  newTag: latest
secretGenerator:
- behavior: replace
  envs:
  - secret.env
  name: devsu-python-app-secrets
generatorOptions:
  disableNameSuffixHash: true
